// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimusPrime.Infrastructure.Persistence;

#nullable disable

namespace OptimusPrime.Infrastructure.Migrations
{
    [DbContext(typeof(OptimusPrimeDbContext))]
    partial class OptimusPrimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("OptimusPrime.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b72793c4-a462-4268-88d8-f080e0eefa42"),
                            Name = "Main"
                        },
                        new
                        {
                            Id = new Guid("d51cc438-6117-4cb2-8d2f-5f33e14d04fc"),
                            Name = "Autobot Cars"
                        },
                        new
                        {
                            Id = new Guid("d74d16ae-2f91-49ce-a741-a00d8ae684ac"),
                            Name = "Mini-Bots"
                        },
                        new
                        {
                            Id = new Guid("be1c56c4-6947-4466-8e07-86542556e576"),
                            Name = "Dinobots"
                        },
                        new
                        {
                            Id = new Guid("24a1832f-cb0c-4770-a559-d4d9fc146c77"),
                            Name = "Aerialbots"
                        },
                        new
                        {
                            Id = new Guid("d9a95247-30f7-4033-83c2-81e45c996619"),
                            Name = "Protectobots"
                        },
                        new
                        {
                            Id = new Guid("83d2f378-26f9-4b83-a562-88ac627a3477"),
                            Name = "Female Autobots"
                        },
                        new
                        {
                            Id = new Guid("3e05f3c6-0e6b-4ac0-8a24-5d5edc818aa6"),
                            Name = "Technobots"
                        },
                        new
                        {
                            Id = new Guid("2fc83505-6cc8-4d5e-930c-5a96fa15f458"),
                            Name = "Throttlebots"
                        },
                        new
                        {
                            Id = new Guid("288870ca-239b-4612-ba27-a9ac1a908c0a"),
                            Name = "Targetmasters"
                        },
                        new
                        {
                            Id = new Guid("76552f0c-9505-4c3d-a2f0-098fc8493a4c"),
                            Name = "Headmasters"
                        },
                        new
                        {
                            Id = new Guid("9fd942c2-9660-4bcb-a70d-74382215c329"),
                            Name = "Clonebots"
                        },
                        new
                        {
                            Id = new Guid("72e18b93-6926-4798-9976-2857d93296fc"),
                            Name = "Junkions"
                        },
                        new
                        {
                            Id = new Guid("78bd17e8-7cd5-4161-9397-2830ef279a74"),
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Infrastructure.Persistence.Entities.Transformer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AllianceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transformers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a78dc38-93c4-413b-8369-7784d8296a00"),
                            AllianceId = 0,
                            CategoryId = new Guid("b72793c4-a462-4268-88d8-f080e0eefa42"),
                            Name = "Optimus Prime"
                        },
                        new
                        {
                            Id = new Guid("33a6a0a1-c13a-4c97-a0a7-c567255299e0"),
                            AllianceId = 0,
                            CategoryId = new Guid("b72793c4-a462-4268-88d8-f080e0eefa42"),
                            Name = "Bumblebee"
                        },
                        new
                        {
                            Id = new Guid("178fb622-a034-4378-a19c-554ee9330512"),
                            AllianceId = 0,
                            CategoryId = new Guid("b72793c4-a462-4268-88d8-f080e0eefa42"),
                            Name = "Cliffjumper"
                        },
                        new
                        {
                            Id = new Guid("ad07477c-e728-42bf-bb0d-54db2688da1c"),
                            AllianceId = 1,
                            CategoryId = new Guid("b72793c4-a462-4268-88d8-f080e0eefa42"),
                            Name = "Megatron"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Infrastructure.Persistence.Entities.Transformer", b =>
                {
                    b.HasOne("OptimusPrime.Infrastructure.Persistence.Entities.Category", "Category")
                        .WithMany("Transformers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OptimusPrime.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Navigation("Transformers");
                });
#pragma warning restore 612, 618
        }
    }
}
