// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimusPrime.Server.Persistences;

namespace OptimusPrime.Server.Migrations
{
    [DbContext(typeof(OptimusPrimeDbContext))]
    [Migration("20190819131017_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("OptimusPrime.Server.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Autobot Cars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mini-Bots"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dinobots"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aerialbots"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Protectobots"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Female Autobots"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Technobots"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Throttlebots"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Targetmasters"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Headmasters"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Clonebots"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Junkions"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Server.Entities.Transformer", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Alliance")
                        .IsRequired();

                    b.Property<int>("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Guid");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transformers");

                    b.HasData(
                        new
                        {
                            Guid = "bd0a9655-d11e-4537-a8c8-65faec607c24",
                            Alliance = "Autobot",
                            CategoryId = 1,
                            Name = "Optimus Prime"
                        },
                        new
                        {
                            Guid = "2d78c5bd-0747-4c0e-9e4a-a7b4678facc9",
                            Alliance = "Autobot",
                            CategoryId = 1,
                            Name = "Bumblebee"
                        },
                        new
                        {
                            Guid = "f261f281-db91-4be2-8acb-feb5c4f3413a",
                            Alliance = "Autobot",
                            CategoryId = 1,
                            Name = "Cliffjumper"
                        },
                        new
                        {
                            Guid = "d1abf070-a87f-4c0b-aa5f-f6a108e6ba87",
                            Alliance = "Decepticon",
                            CategoryId = 1,
                            Name = "Megatron"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Server.Entities.Transformer", b =>
                {
                    b.HasOne("OptimusPrime.Server.Entities.Category", "Category")
                        .WithMany("Transformers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
