// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimusPrime.Server.Persistences;

namespace OptimusPrime.Server.Migrations
{
    [DbContext(typeof(OptimusPrimeDbContext))]
    partial class OptimusPrimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("OptimusPrime.Server.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Autobots"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Server.Entities.Transformer", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Alliance")
                        .IsRequired();

                    b.Property<int>("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Guid");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transformers");

                    b.HasData(
                        new
                        {
                            Guid = "d91e068b-6708-41d5-8fb7-da03f7bdf1db",
                            Alliance = "Autobot",
                            CategoryId = 1,
                            Name = "Bumblebee"
                        });
                });

            modelBuilder.Entity("OptimusPrime.Server.Entities.Transformer", b =>
                {
                    b.HasOne("OptimusPrime.Server.Entities.Category", "Category")
                        .WithMany("Transformers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
