// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimusPrime.Server.Persistences;

namespace OptimusPrime.Server.Migrations
{
    [DbContext(typeof(OptimusPrimeDbContext))]
    partial class OptimusPrimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("OptimusPrime.Server.Entities.Transformer", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Guid");

                    b.ToTable("Transformers");

                    b.HasData(
                        new
                        {
                            Guid = "96543483-7f27-445f-a30b-08b11248afe9",
                            Name = "Bumblebee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
